#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.M3{1,0,7.2,1
#
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/hello_pm3g.om3g.dep
package/cfg/hello_pm3g.om3g.dep: ;
endif

package/cfg/hello_pm3g.om3g: | .interfaces
package/cfg/hello_pm3g.om3g: package/cfg/hello_pm3g.c package/cfg/hello_pm3g.mak 
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -mcpu=cortex-m3 -march=armv7-m -mthumb -mfloat-abi=soft -DDeviceFamily_CC26X0R2 -I"D:/2_Programing/2_LaunchXL/1_TestCodeWorkspace/hello_CC2640R2_LAUNCHXL_tirtos_gcc" -I"C:/ti/simplelink_cc2640r2_sdk_4_40_00_10/source/ti/posix/gcc" -I"C:/ti/simplelink_cc2640r2_sdk_4_40_00_10/kernel/tirtos/packages/gnu/targets/arm/libs/install-native/arm-none-eabi/include/newlib-nano" -I"C:/ti/simplelink_cc2640r2_sdk_4_40_00_10/kernel/tirtos/packages/gnu/targets/arm/libs/install-native/arm-none-eabi/include" -I"C:/ti/ccs1030/ccs/tools/compiler/gcc-arm-none-eabi-7-2017-q4-major-win32/arm-none-eabi/include" -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -Wall  -std=c99  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__   -Dxdc_cfg__xheader__='"configPkg/package/cfg/hello_pm3g.h"'  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_7_2_1  -O2   $(XDCINCS) -IC:/ti/simplelink_cc2640r2_sdk_4_40_00_10/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -IC:/ti/simplelink_cc2640r2_sdk_4_40_00_10/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/cfg/hello_pm3g.om3g: export LD_LIBRARY_PATH=

package/cfg/hello_pm3g.sm3g: | .interfaces
package/cfg/hello_pm3g.sm3g: package/cfg/hello_pm3g.c package/cfg/hello_pm3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -mcpu=cortex-m3 -march=armv7-m -mthumb -mfloat-abi=soft -DDeviceFamily_CC26X0R2 -I"D:/2_Programing/2_LaunchXL/1_TestCodeWorkspace/hello_CC2640R2_LAUNCHXL_tirtos_gcc" -I"C:/ti/simplelink_cc2640r2_sdk_4_40_00_10/source/ti/posix/gcc" -I"C:/ti/simplelink_cc2640r2_sdk_4_40_00_10/kernel/tirtos/packages/gnu/targets/arm/libs/install-native/arm-none-eabi/include/newlib-nano" -I"C:/ti/simplelink_cc2640r2_sdk_4_40_00_10/kernel/tirtos/packages/gnu/targets/arm/libs/install-native/arm-none-eabi/include" -I"C:/ti/ccs1030/ccs/tools/compiler/gcc-arm-none-eabi-7-2017-q4-major-win32/arm-none-eabi/include" -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -Wall  -std=c99  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__   -Dxdc_cfg__xheader__='"configPkg/package/cfg/hello_pm3g.h"'  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_7_2_1  -O2   $(XDCINCS) -IC:/ti/simplelink_cc2640r2_sdk_4_40_00_10/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -IC:/ti/simplelink_cc2640r2_sdk_4_40_00_10/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/cfg/hello_pm3g.sm3g: export LD_LIBRARY_PATH=

clean,m3g ::
	-$(RM) package/cfg/hello_pm3g.om3g
	-$(RM) package/cfg/hello_pm3g.sm3g

hello.pm3g: package/cfg/hello_pm3g.om3g package/cfg/hello_pm3g.mak

clean::
	-$(RM) package/cfg/hello_pm3g.mak
